services:
  db:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: dayrise/oc_lettings_web:latest
    build: .
    environment:
      - DEBUG="False"
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./logs:/app/logs
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: dayrise/oc_lettings_nginx:latest
    build: ./nginx
    ports:
      - 8181:80
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles
    

volumes:
  postgres_data:
  static_volume: