# Generated by Django 5.0.6 on 2024-05-09 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # We want to use the renamed tables from migration
    # "0003_remove_letting_address_delete_address_delete_letting" so we have to make
    # sure this migration is applied after.
    dependencies = [
        (
            "oc_lettings_site",
            "0003_remove_letting_address_delete_address_delete_letting",
        ),
    ]

    # Now we prevent Django from creating the tables as they already exist
    # cf. https://realpython.com/move-django-model/#the-django-way-rename-the-table
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Address",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "number",
                            models.PositiveIntegerField(
                                validators=[
                                    django.core.validators.MaxValueValidator(9999)
                                ]
                            ),
                        ),
                        ("street", models.CharField(max_length=64)),
                        ("city", models.CharField(max_length=64)),
                        (
                            "state",
                            models.CharField(
                                max_length=2,
                                validators=[
                                    django.core.validators.MinLengthValidator(2)
                                ],
                            ),
                        ),
                        (
                            "zip_code",
                            models.PositiveIntegerField(
                                validators=[
                                    django.core.validators.MaxValueValidator(99999)
                                ]
                            ),
                        ),
                        (
                            "country_iso_code",
                            models.CharField(
                                max_length=3,
                                validators=[
                                    django.core.validators.MinLengthValidator(3)
                                ],
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name="Letting",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=256)),
                        (
                            "address",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="lettings.address",
                            ),
                        ),
                    ],
                ),
            ],
            database_operations=[],
        ),
    ]
