# Generated by Django 5.0.6 on 2024-05-09 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0002_alter_address_id_alter_letting_id_alter_profile_id"),
    ]

    # In context of migrating the models to an other app, we don't want to actually
    # delete the FK and the models. For more details:
    # https://realpython.com/move-django-model/#the-django-way-rename-the-table
    operations = [
        migrations.SeparateDatabaseAndState(
            # So the ORM state is updated
            state_operations=[
                migrations.RemoveField(
                    model_name="letting",
                    name="address",
                ),
                migrations.DeleteModel(
                    name="Address",
                ),
                migrations.DeleteModel(
                    name="Letting",
                ),
            ],
            # Instead of dropping the tables, we rename them
            database_operations=[
                migrations.AlterModelTable(
                    name="Address",
                    table="lettings_address",
                ),
                migrations.AlterModelTable(
                    name="Letting",
                    table="lettings_letting",
                ),
            ],
        ),
    ]
