# Generated by Django 5.0.6 on 2024-05-13 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "oc_lettings_site",
            "0003_remove_letting_address_delete_address_delete_letting",
        ),
    ]

    # In context of migrating Profile model to an other app, we will rename the table
    # instead of deleting it. For more details:
    # https://realpython.com/move-django-model/#the-django-way-rename-the-table
    operations = [
        migrations.SeparateDatabaseAndState(
            # So the ORM state is updated
            state_operations=[
                migrations.DeleteModel(
                    name="Profile",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Profile",
                    table="profiles_profile",
                ),
            ],
        ),
    ]
